services:
  web:
    image: clearthesky_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3995:8080"
    environment:
      - TZ=Europe/Amsterdam
      - ASPNETCORE_ENVIRONMENT=Production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - asp_net_data:/root/.aspnet
    command: dotnet ClearTheSky.dll
    
  shell:
    image: clearthesky_image
    environment:
      - TZ=Europe/Amsterdam
      - ASPNETCORE_ENVIRONMENT=Production
    profiles:
      - manual
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: no
    depends_on:
      - db
    entrypoint: bash

    
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleartheksy_prod
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    
volumes:
  db_data:
  asp_net_data:
